/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.editor.jsonc --env-file=worker/empty.env --include-runtime=false --env-interface=EditorProductionEnv worker/config-editor/bindings.production.d.ts` (hash: ec8aa37776af0479f7e4418b5a19c1c4)
interface __BaseEnv_EditorProductionEnv {
	EDITOR_PAYLOADS: R2Bucket;
	EDITOR_SESSION_CREATES: RateLimit;
	EDITOR_SESSION_TRAFFIC: RateLimit;
	ASSETS: Fetcher;
	EDITOR_SESSIONS: DurableObjectNamespace<import("./index").EditorSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "EditorSession";
	}
	interface Env extends __BaseEnv_EditorProductionEnv {}
}
interface EditorProductionEnv extends __BaseEnv_EditorProductionEnv {}
