/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.editor.local.jsonc --env-file=worker/empty.env --include-runtime=false --env-interface=EditorLocalEnv worker/config-editor/bindings.local.d.ts` (hash: 32c17946a68dbe7cf7360325cdf843c8)
interface __BaseEnv_EditorLocalEnv {
	EDITOR_PAYLOADS: R2Bucket;
	EDITOR_SESSION_CREATES: RateLimit;
	EDITOR_SESSION_TRAFFIC: RateLimit;
	ASSETS: Fetcher;
	EDITOR_DAILY_SESSION_LIMIT: "500";
	EDITOR_HOURLY_SESSION_LIMIT: "100";
	EDITOR_SESSIONS: DurableObjectNamespace<import("./index").EditorSession>;
	EDITOR_ADMISSION: DurableObjectNamespace<import("./index").EditorAdmission>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "EditorSession" | "EditorAdmission";
	}
	interface Env extends __BaseEnv_EditorLocalEnv {}
}
interface EditorLocalEnv extends __BaseEnv_EditorLocalEnv {}
