/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.editor.local.jsonc --env-file=worker/empty.env --include-runtime=false --env-interface=EditorLocalEnv worker/config-editor/bindings.local.d.ts` (hash: 192863be22dbb64d33ebcc813c757a94)
interface __BaseEnv_EditorLocalEnv {
	EDITOR_PAYLOADS: R2Bucket;
	EDITOR_SESSION_CREATES: RateLimit;
	EDITOR_SESSION_TRAFFIC: RateLimit;
	ASSETS: Fetcher;
	EDITOR_SESSIONS: DurableObjectNamespace<import("./index").EditorSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "EditorSession";
	}
	interface Env extends __BaseEnv_EditorLocalEnv {}
}
interface EditorLocalEnv extends __BaseEnv_EditorLocalEnv {}
