/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.editor.local.jsonc --env-file=worker/empty.env --include-runtime=false --env-interface=EditorLocalEnv worker/config-editor/bindings.local.d.ts` (hash: e22d647a3c728f4bdf1bd71c59e2dd8b)
interface __BaseEnv_EditorLocalEnv {
	EDITOR_PAYLOADS: R2Bucket;
	EDITOR_SESSION_CREATES: RateLimit;
	EDITOR_SESSION_TRAFFIC: RateLimit;
	ASSETS: Fetcher;
	EDITOR_DAILY_SESSION_LIMIT: "500";
	EDITOR_HOURLY_SESSION_LIMIT: "100";
	EDITOR_SESSIONS: DurableObjectNamespace<import("./index").EditorSession>;
	EDITOR_ADMISSION: DurableObjectNamespace<import("./index").EditorAdmission>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "EditorSession" | "EditorAdmission";
	}
	interface Env extends __BaseEnv_EditorLocalEnv {}
}
interface EditorLocalEnv extends __BaseEnv_EditorLocalEnv {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}