/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.editor.jsonc --env-file=worker/empty.env --include-runtime=false --env-interface=EditorProductionEnv worker/config-editor/bindings.production.d.ts` (hash: ca77fdf42c1706aabb8341163e1b0a9d)
interface __BaseEnv_EditorProductionEnv {
	EDITOR_PAYLOADS: R2Bucket;
	EDITOR_SESSION_CREATES: RateLimit;
	EDITOR_SESSION_TRAFFIC: RateLimit;
	ASSETS: Fetcher;
	EDITOR_DAILY_SESSION_LIMIT: "500";
	EDITOR_HOURLY_SESSION_LIMIT: "100";
	EDITOR_SESSIONS: DurableObjectNamespace<import("./index").EditorSession>;
	EDITOR_ADMISSION: DurableObjectNamespace<import("./index").EditorAdmission>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "EditorSession" | "EditorAdmission";
	}
	interface Env extends __BaseEnv_EditorProductionEnv {}
}
interface EditorProductionEnv extends __BaseEnv_EditorProductionEnv {}
