DELETE FROM server_status WHERE server_id LIKE 'local-%';
DELETE FROM server_status WHERE server_id LIKE 'real-%';
DELETE FROM moderation_events WHERE server_id LIKE 'local-%';
DELETE FROM moderation_events WHERE server_id LIKE 'real-%';
DELETE FROM submissions WHERE server_id LIKE 'local-%';
DELETE FROM submissions WHERE server_id LIKE 'real-%';
DELETE FROM servers WHERE id LIKE 'local-%';
DELETE FROM servers WHERE id LIKE 'real-%';

INSERT OR REPLACE INTO servers (
  id,
  slug,
  name,
  description,
  normalized_host,
  port,
  website_url,
  social_links_json,
  status,
  featured_rank,
  approved_at,
  created_at,
  updated_at
) VALUES
  (
    'local-hypixel',
    'hypixel',
    'Hypixel',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae risus non lorem aliquet malesuada.',
    'mc.hypixel.net',
    25565,
    'https://hypixel.net/',
    '[{"key":"discord","label":"Discord","url":"https://discord.com/","host":"discord.com"},{"key":"youtube","label":"YouTube","url":"https://youtube.com/","host":"youtube.com"},{"key":"x","label":"X","url":"https://x.com/","host":"x.com"}]',
    'approved',
    120,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-cubecraft',
    'cubecraft',
    'CubeCraft',
    'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
    'play.cubecraft.net',
    25565,
    'https://cubecraft.net/',
    '[{"key":"discord","label":"Discord","url":"https://discord.com/","host":"discord.com"}]',
    'approved',
    110,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-minehut',
    'minehut',
    'Minehut',
    'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.',
    'mc.minehut.com',
    25565,
    'https://minehut.com/',
    '[]',
    'approved',
    100,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-manacube',
    'manacube',
    'ManaCube',
    'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus.',
    'mc.manacube.com',
    25565,
    'https://manacube.com/',
    '[{"key":"discord","label":"Discord","url":"https://discord.com/","host":"discord.com"},{"key":"youtube","label":"YouTube","url":"https://youtube.com/","host":"youtube.com"},{"key":"x","label":"X","url":"https://x.com/","host":"x.com"}]',
    'approved',
    90,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-wynncraft',
    'wynncraft',
    'Wynncraft',
    'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet.',
    'play.wynncraft.com',
    25565,
    'https://wynncraft.com/',
    '[{"key":"youtube","label":"YouTube","url":"https://youtube.com/","host":"youtube.com"}]',
    'approved',
    80,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-complex',
    'complex-gaming',
    'Complex Gaming',
    'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores.',
    'hub.mc-complex.com',
    25565,
    'https://mc-complex.com/',
    '[{"key":"discord","label":"Discord","url":"https://discord.com/","host":"discord.com"},{"key":"facebook","label":"Facebook","url":"https://facebook.com/","host":"facebook.com"},{"key":"instagram","label":"Instagram","url":"https://instagram.com/","host":"instagram.com"},{"key":"x","label":"X","url":"https://x.com/","host":"x.com"},{"key":"youtube","label":"YouTube","url":"https://youtube.com/","host":"youtube.com"}]',
    'approved',
    70,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-purple-prison',
    'purple-prison',
    'Purple Prison',
    'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam.',
    'purpleprison.org',
    25565,
    'https://purpleprison.org/',
    '[{"key":"discord","label":"Discord","url":"https://discord.com/","host":"discord.com"}]',
    'approved',
    60,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-blossomcraft',
    'blossomcraft',
    'BlossomCraft',
    'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae.',
    'ms.blossomcraft.org',
    25565,
    'https://blossomcraft.org/',
    '[]',
    'approved',
    50,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-earthmc',
    'earthmc',
    'EarthMC',
    'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.',
    'top.earthmc.net',
    25565,
    'https://earthmc.net/',
    '[{"key":"discord","label":"Discord","url":"https://discord.com/","host":"discord.com"},{"key":"x","label":"X","url":"https://x.com/","host":"x.com"}]',
    'approved',
    40,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-extremecraft',
    'extremecraft',
    'ExtremeCraft',
    'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.',
    'sl.extremecraft.net',
    25565,
    'https://extremecraft.net/',
    '[{"key":"discord","label":"Discord","url":"https://discord.com/","host":"discord.com"},{"key":"youtube","label":"YouTube","url":"https://youtube.com/","host":"youtube.com"}]',
    'approved',
    30,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-pikanetwork',
    'pikanetwork',
    'PikaNetwork',
    'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit.',
    'go.pika.host',
    25565,
    'https://pika-network.net/',
    '[{"key":"discord","label":"Discord","url":"https://discord.com/","host":"discord.com"}]',
    'approved',
    20,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-jartex',
    'jartex-network',
    'JartexNetwork',
    'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla.',
    'top.jartex.fun',
    25565,
    'https://jartexnetwork.com/',
    '[{"key":"facebook","label":"Facebook","url":"https://facebook.com/","host":"facebook.com"},{"key":"instagram","label":"Instagram","url":"https://instagram.com/","host":"instagram.com"},{"key":"youtube","label":"YouTube","url":"https://youtube.com/","host":"youtube.com"}]',
    'approved',
    10,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  ),
  (
    'local-pending-1',
    'pending-review-server',
    'Pending Review Server',
    'A local pending record for testing moderation queue behavior.',
    'servers.kingdomsx.com',
    25565,
    NULL,
    '[]',
    'pending',
    0,
    NULL,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  );

INSERT OR REPLACE INTO submissions (
  id,
  server_id,
  contact,
  verification_method,
  verification_evidence,
  submitter_ip_hash,
  user_agent_hash,
  turnstile_result,
  moderation_notes,
  created_at
) VALUES (
  'local-submission-1',
  'local-pending-1',
  'AfkF24',
  'legacy_console_output',
  'Kingdoms version: v1.17.27.1.1 platform: Paper',
  'local-ip-hash',
  'local-user-agent-hash',
  '{"success":true,"local":true}',
  NULL,
  strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
);

INSERT OR REPLACE INTO moderation_events (
  id,
  server_id,
  actor,
  action,
  notes,
  created_at
) VALUES
  ('local-event-hypixel', 'local-hypixel', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-cubecraft', 'local-cubecraft', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-minehut', 'local-minehut', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-manacube', 'local-manacube', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-wynncraft', 'local-wynncraft', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-complex', 'local-complex', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-purple-prison', 'local-purple-prison', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-blossomcraft', 'local-blossomcraft', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-earthmc', 'local-earthmc', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-extremecraft', 'local-extremecraft', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-pikanetwork', 'local-pikanetwork', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-jartex', 'local-jartex', 'system', 'approved', 'Seeded approved listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  ('local-event-pending-1', 'local-pending-1', 'system', 'submitted', 'Seeded pending listing for local development.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
