/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.server-directory.local.jsonc --env-file=worker/empty.env --include-runtime=false --env-interface=ServerDirectoryLocalEnv worker/server-directory/bindings.local.d.ts` (hash: 9711ea9c7d6c3ddec6d8971a5e2a9470)
interface __BaseEnv_ServerDirectoryLocalEnv {
	DB: D1Database;
	PLUGIN_VERIFY_RATE_LIMIT: RateLimit;
	PLUGIN_VERIFY_GLOBAL_RATE_LIMIT: RateLimit;
	VERIFICATION_CREATE_RATE_LIMIT: RateLimit;
	PUBLIC_API_RATE_LIMIT: RateLimit;
	PUBLIC_API_LOCATION_RATE_LIMIT: RateLimit;
	VERIFICATION_CREATE_ACCOUNT_RATE_LIMIT: RateLimit;
	SUBMITTER_READ_RATE_LIMIT: RateLimit;
	VERIFICATION_STATUS_ACCOUNT_RATE_LIMIT: RateLimit;
	PUBLIC_DETAILS_MUTATION_RATE_LIMIT: RateLimit;
	SUBMISSION_MUTATION_RATE_LIMIT: RateLimit;
	VERIFICATION_STATUS_RATE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	APP_ENVIRONMENT: "local";
	RATE_LIMIT_SALT: string;
	VERIFICATION_CODE_SECRET: string;
	SESSION_SECRET: string;
	LOCAL_ADMIN_TOKEN: string;
	TURNSTILE_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DISCORD_GUILD_ID: string;
	DISCORD_REDIRECT_URI: string;
	DISCORD_SERVER_DIRECTORY_WEBHOOK_URL: string;
	DISCORD_SERVER_REVIEW_WEBHOOK_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_ServerDirectoryLocalEnv {}
}
interface ServerDirectoryLocalEnv extends __BaseEnv_ServerDirectoryLocalEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENVIRONMENT" | "RATE_LIMIT_SALT" | "VERIFICATION_CODE_SECRET" | "SESSION_SECRET" | "LOCAL_ADMIN_TOKEN" | "TURNSTILE_SECRET" | "DISCORD_CLIENT_ID" | "DISCORD_CLIENT_SECRET" | "DISCORD_GUILD_ID" | "DISCORD_REDIRECT_URI" | "DISCORD_SERVER_DIRECTORY_WEBHOOK_URL" | "DISCORD_SERVER_REVIEW_WEBHOOK_URL">> {}
}
