/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.server-directory.jsonc --env-file=worker/empty.env --include-runtime=false --env-interface=ServerDirectoryProductionEnv worker/server-directory/bindings.production.d.ts` (hash: b6e074be00643dd58ca982afafb1577d)
interface __BaseEnv_ServerDirectoryProductionEnv {
	DB: D1Database;
	PLUGIN_VERIFY_RATE_LIMIT: RateLimit;
	PLUGIN_VERIFY_GLOBAL_RATE_LIMIT: RateLimit;
	VERIFICATION_CREATE_RATE_LIMIT: RateLimit;
	PUBLIC_API_RATE_LIMIT: RateLimit;
	PUBLIC_API_LOCATION_RATE_LIMIT: RateLimit;
	VERIFICATION_CREATE_ACCOUNT_RATE_LIMIT: RateLimit;
	SUBMITTER_READ_RATE_LIMIT: RateLimit;
	VERIFICATION_STATUS_ACCOUNT_RATE_LIMIT: RateLimit;
	PUBLIC_DETAILS_MUTATION_RATE_LIMIT: RateLimit;
	SUBMISSION_MUTATION_RATE_LIMIT: RateLimit;
	VERIFICATION_STATUS_RATE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	APP_ENVIRONMENT: "production";
	TURNSTILE_SECRET: string;
	RATE_LIMIT_SALT: string;
	VERIFICATION_CODE_SECRET: string;
	SESSION_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DISCORD_GUILD_ID: string;
	DISCORD_REDIRECT_URI: string;
	ADMIN_EMAILS: string;
	CF_ACCESS_TEAM_DOMAIN: string;
	CF_ACCESS_AUD: string;
	DISCORD_SERVER_DIRECTORY_WEBHOOK_URL: string;
	DISCORD_SERVER_REVIEW_WEBHOOK_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_ServerDirectoryProductionEnv {}
}
interface ServerDirectoryProductionEnv extends __BaseEnv_ServerDirectoryProductionEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENVIRONMENT" | "TURNSTILE_SECRET" | "RATE_LIMIT_SALT" | "VERIFICATION_CODE_SECRET" | "SESSION_SECRET" | "DISCORD_CLIENT_ID" | "DISCORD_CLIENT_SECRET" | "DISCORD_GUILD_ID" | "DISCORD_REDIRECT_URI" | "ADMIN_EMAILS" | "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "DISCORD_SERVER_DIRECTORY_WEBHOOK_URL" | "DISCORD_SERVER_REVIEW_WEBHOOK_URL">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}