/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=ProductionEnv worker/bindings.production.d.ts` (hash: 2ef0aa8ae06322720d2b116b4a3af5ca)
interface __BaseEnv_ProductionEnv {
	DB: D1Database;
	PLUGIN_VERIFY_RATE_LIMIT: RateLimit;
	PLUGIN_VERIFY_GLOBAL_RATE_LIMIT: RateLimit;
	VERIFICATION_CREATE_RATE_LIMIT: RateLimit;
	PUBLIC_API_RATE_LIMIT: RateLimit;
	PUBLIC_API_LOCATION_RATE_LIMIT: RateLimit;
	VERIFICATION_CREATE_ACCOUNT_RATE_LIMIT: RateLimit;
	SUBMITTER_READ_RATE_LIMIT: RateLimit;
	VERIFICATION_STATUS_ACCOUNT_RATE_LIMIT: RateLimit;
	PUBLIC_DETAILS_MUTATION_RATE_LIMIT: RateLimit;
	SUBMISSION_MUTATION_RATE_LIMIT: RateLimit;
	VERIFICATION_STATUS_RATE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	APP_ENVIRONMENT: "production";
	TURNSTILE_SECRET: string;
	RATE_LIMIT_SALT: string;
	VERIFICATION_CODE_SECRET: string;
	SESSION_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DISCORD_GUILD_ID: string;
	DISCORD_REDIRECT_URI: string;
	ADMIN_EMAILS: string;
	CF_ACCESS_TEAM_DOMAIN: string;
	CF_ACCESS_AUD: string;
	DISCORD_SERVER_DIRECTORY_WEBHOOK_URL: string;
	DISCORD_SERVER_REVIEW_WEBHOOK_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ProductionEnv {}
}
interface ProductionEnv extends __BaseEnv_ProductionEnv {}
