/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.local.jsonc --include-runtime=false --env-interface=LocalEnv worker/bindings.local.d.ts` (hash: 7fee61e17c33c784bba4860a640a5c11)
interface __BaseEnv_LocalEnv {
	DB: D1Database;
	PLUGIN_VERIFY_RATE_LIMIT: RateLimit;
	PLUGIN_VERIFY_GLOBAL_RATE_LIMIT: RateLimit;
	VERIFICATION_CREATE_RATE_LIMIT: RateLimit;
	PUBLIC_API_RATE_LIMIT: RateLimit;
	PUBLIC_API_LOCATION_RATE_LIMIT: RateLimit;
	VERIFICATION_CREATE_ACCOUNT_RATE_LIMIT: RateLimit;
	SUBMITTER_READ_RATE_LIMIT: RateLimit;
	VERIFICATION_STATUS_ACCOUNT_RATE_LIMIT: RateLimit;
	PUBLIC_DETAILS_MUTATION_RATE_LIMIT: RateLimit;
	SUBMISSION_MUTATION_RATE_LIMIT: RateLimit;
	VERIFICATION_STATUS_RATE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	APP_ENVIRONMENT: "local";
	RATE_LIMIT_SALT: string;
	VERIFICATION_CODE_SECRET: string;
	SESSION_SECRET: string;
	LOCAL_ADMIN_TOKEN: string;
	TURNSTILE_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DISCORD_GUILD_ID: string;
	DISCORD_REDIRECT_URI: string;
	DISCORD_SERVER_DIRECTORY_WEBHOOK_URL: string;
	DISCORD_SERVER_REVIEW_WEBHOOK_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_LocalEnv {}
}
interface LocalEnv extends __BaseEnv_LocalEnv {}
