/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env-file=worker/empty.env --include-runtime=false --env-interface=ProductionEnv worker/bindings.production.d.ts` (hash: 327755779d33af03a50b73dc9f884e7b)
interface __BaseEnv_ProductionEnv {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ProductionEnv {}
}
interface ProductionEnv extends __BaseEnv_ProductionEnv {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}