/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env-file=worker/empty.env --include-runtime=false --env-interface=ProductionEnv worker/bindings.production.d.ts` (hash: 084f6d6d5f7fcf0433c98bfece4d02ea)
interface __BaseEnv_ProductionEnv {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ProductionEnv {}
}
interface ProductionEnv extends __BaseEnv_ProductionEnv {}
